version: '3.8'

services:
  wordpress:
    build:
      context: ./wordpress
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network_wordpress

  db:
    image: mysql:oracle
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network_wordpress


networks:
  network_wordpress:
